# Generated by Django 4.2.5 on 2023-09-20 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('proof_no', models.PositiveIntegerField()),
                ('prev_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_data', models.JSONField(default=list)),
                ('chain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coin.block')),
            ],
        ),
    ]
